package functionalities;

import objects.Currency;
import utils.MessageIDGenerator;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;

import static utils.Constants.*;
import static utils.SocketFunctions.sendRequest;
import static utils.UtilityFunctions.*;


public class ClientInterface {
    public static MessageIDGenerator gen = new MessageIDGenerator(MESSAGE_ID_LENGTH);   // create a new MessageIDGenerator

    /**
     * Function to process account creation
     *
     * @param name              String containing name of the customer
     * @param currency          Enum to represent the currency of the bank account
     * @param password          String to represent password of the bank account
     * @param initialAccBalance String to represent inital account balance
     * @return the bank account number generated by the server
     */
    public static int createAccount(String name, Currency currency, String password, String initialAccBalance) {

        byte[] accCreationByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(ACC_OPENING_CODE).array();

        byte[] nameByteArray = marshall(name);
        byte[] currencyByteArray = marshall(currency.name());
        byte[] passwordByteArray = marshall(password);
        byte[] accBalanceArray = marshall(initialAccBalance);

        String messageID = gen.nextString();
        System.out.println(messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);

        byte[] marshall = concatWithCopy(messageIDArray, accCreationByteArray, nameByteArray, currencyByteArray, passwordByteArray, accBalanceArray);
        for (byte c : marshall) {
            System.out.printf("%02X ", c);      // printing to show the marshalled data on console
        }
        System.out.println();
        byte[] reply = sendRequest(marshall);

        ByteBuffer choiceBuffer = ByteBuffer.allocate(BUFFER_SIZE);
        choiceBuffer.put(reply);
        choiceBuffer.rewind();
        return choiceBuffer.getInt();
    }

    /**
     * Function to query current account balance
     *
     * @param accNumber the account number of the account to be queried
     * @param password  the password of the account to be queried
     * @return the current balance in the account
     */
    public static double queryAccBalance(String accNumber, String password) {
        /*
        int accNumberLength = accNumber.length();
        int passwordLength = password.length();
        */

        byte[] accBalanceQueryByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(ACC_BALANCE_CODE).array();

        /*
        byte[] accNumberLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(accNumberLength).array();
        byte[] accNumberByteArray = convertStringToByteArray(accNumber);

        byte[] passwordLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);

         */

        byte[] accNumberByteArray = marshall(accNumber);
        byte[] passwordByteArray = marshall(password);

        String messageID = gen.nextString();
        System.out.println(messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);

        byte[] marshall = concatWithCopy(messageIDArray, accBalanceQueryByteArray, accNumberByteArray, passwordByteArray);
        for (byte c : marshall) {
            System.out.printf("%02X ", c);      // printing to show the marshalled data on console
        }
        System.out.println();
        byte[] reply = sendRequest(marshall);

        double currentAccBalance = ByteBuffer.wrap(reply).getDouble();
        System.out.printf("current account balance: %.2f\n", currentAccBalance);
        return currentAccBalance;
    }

    public static String closeAccount(String name, String password, String accNumber) {
        int nameLength = name.length();
        int passwordLength = password.length();
        int accNumberLength = accNumber.length();

        byte[] closeAccByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(ACC_CLOSING_CODE).array();

        byte[] accNumberLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(accNumberLength).array();
        byte[] accNumberByteArray = convertStringToByteArray(accNumber);

        byte[] nameLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(nameLength).array();
        byte[] nameByteArray = convertStringToByteArray(name);

        byte[] passwordLengthByteArray = ByteBuffer.allocate(BYTE_BLOCK_SIZE_FOR_INT).putInt(passwordLength).array();
        byte[] passwordByteArray = convertStringToByteArray(password);

        String messageID = gen.nextString();
        System.out.println(messageID);
        byte[] messageIDArray = convertStringToByteArray(messageID);

        byte[] marshall = concatWithCopy(messageIDArray, closeAccByteArray, accNumberLengthByteArray, accNumberByteArray, nameLengthByteArray, nameByteArray, passwordLengthByteArray, passwordByteArray);
        for (byte c : marshall) {
            System.out.printf("%02X ", c);      // printing to show the marshalled data on console
        }
        System.out.println();
        String reply = new String(sendRequest(marshall), StandardCharsets.UTF_8);

        if (reply.equals(accNumber)) {
            return "Account Number " + reply + " has been closed successfully";
        }

        return " ";
    }
}
